Feature/rabbitmq
IKNL/vantage6 pull request #91
Opened 2022-03-31 13:45 UTC by bartvanb

- Starts a RabbitMQ image on startup
- Introduces RabbitMQ manager to manage the rabbitmq container
- Modifies startup command: not using vserver-local any more, but uwsgi
- configuration adapted to include RabbitMQ
- Removing rabbitmq container in `vserver stop`.
- adapated unittests

2022-04-04 12:49 UTC, frankcorneliusmartin requested changes

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/configuration_wizard.py
> +    if is_add_rabbitmq:
Wouldnt it be better to generate something secure? right now it feels like the queue already exists, thus that they already need the `username` and `password` to login (and not that they can pick one themselfs).

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +        f"host.docker.internal:{QUEUE_PORT}/{VHOST}"
`host.docker.internal` is not a good hostname. its would be better to use the hostname you define when starting the container: 

`hostname=f'{APPNAME}-{self.ctx.name}-rabbit',` L99

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +            hostname=f'{APPNAME}-{self.ctx.name}-rabbit',
> this hostname

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +        # TODO make the time / # attempts settable? Is this enough time (5m)?
move to the constants module

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +            exit(0)
i think an `exit(1)` would be more appriopiate as `0` is generally considered a succesfull termination as if it is intended

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +        definitions_filepath = Path(self.ctx.data_dir / 'definitions.json')
I think it would be good to make this a module constant, so we only need to change it at one spot

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +            Path(os.path.dirname(os.path.realpath(__file__))) / RABBIT_CONFIG
Why not start refering after creating a `Path`?
 `Path(__file__).resolve().parent`

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +        if not os.path.exists(rabbit_data_dir):
Also big in favor of using `Path` objects. This would simplify to:
`rabbit_data_dir.exists()`

2022-04-04 12:49 UTC, frankcorneliusmartin commented on vantage6/cli/rabbitmq/queue_manager.py
> +            os.makedirs(rabbit_data_dir)
`rabbit_data_dir.mkdir()`

2022-04-04 13:10 UTC, merged

2022-04-05 09:38 UTC, bartvanb commented on vantage6/cli/configuration_wizard.py
> +    if is_add_rabbitmq:
I've tried to tackle this by generating a random string as password and adding 'new' to the question